# Generated by Django 3.1 on 2020-09-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trails',
            old_name='sto',
            new_name='stocks',
        ),
    ]
