# Generated by Django 4.0.1 on 2022-01-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyTips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
